version: 0.2

env:
    variables:
        S3_BUCKET: ""
phases:
  install:
    runtime-versions:
        dotnet: 3.1    
    commands:
      - dotnet tool install -g trx2junit
      - dotnet tool install -g Amazon.Lambda.Tools
  pre_build:
    commands:
      - cd ./ServerlessAwsSdkChangeLogAPI.UnitTests
      - dotnet test -c Release  --logger trx --results-directory ../testresults
      - cd ..
  build:
    commands:
      - cd ./ServerlessAwsSdkChangeLogAPI
      - /root/.dotnet/tools/dotnet-lambda package-ci --config-file codebuild-defaults.json --serverless-template serverless.template --output-template updated.template --s3-bucket $S3_BUCKET --s3-prefix ServerlessAwsSdkChangeLogAPIPackageCIArtifacts/
      - cd ..
    post_build:
      commands:
        - ~/.dotnet/tools/trx2junit ./testresults/*
reports:
  ServerlessAwsSdkChangeLogAPI-UnitTests:
    files:
      - '**/*'
    base-directory: './testresults'         
artifacts:
  files:
    - ./ServerlessAwsSdkChangeLogAPI/updated.template
  discard-paths: yes